/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-03-25 05:58:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html ng-app=\"WaterPlant\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Dashboard - Water Plant</title>\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/responsive.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/metisMenu.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/nv.d3.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"external-js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"  src=\"external-js/angular.min.js\"></script>\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf8\"\tsrc=\"external-js/jquery.dataTables.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\tsrc=\"external-js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/metisMenu.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/d3.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/nv.d3.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/angular-nvd3.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"JS/Dashboard.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#masterload').load(\"Menu.jsp\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("  window.onload = function () {\r\n");
      out.write("    var chart = new CanvasJS.Chart(\"chartContainer\",\r\n");
      out.write("    {\r\n");
      out.write("      title:{\r\n");
      out.write("        text: \"A Multi-series Column Chart\"\r\n");
      out.write("      \r\n");
      out.write("      },   \r\n");
      out.write("      data: [{        \r\n");
      out.write("        type: \"column\",\r\n");
      out.write("        dataPoints: [\r\n");
      out.write("        { x: 10, y: 171 },\r\n");
      out.write("        { x: 20, y: 155},\r\n");
      out.write("        { x: 30, y: 150 },\r\n");
      out.write("        { x: 40, y: 165 },\r\n");
      out.write("        { x: 50, y: 195 },\r\n");
      out.write("        { x: 60, y: 168 },\r\n");
      out.write("        { x: 70, y: 128 },\r\n");
      out.write("        { x: 80, y: 134 },\r\n");
      out.write("        { x: 90, y: 114}\r\n");
      out.write("        ]\r\n");
      out.write("      },\r\n");
      out.write("      {        \r\n");
      out.write("        type: \"column\",\r\n");
      out.write("        dataPoints: [\r\n");
      out.write("        { x: 10, y: 71 },\r\n");
      out.write("        { x: 20, y: 55},\r\n");
      out.write("        { x: 30, y: 50 },\r\n");
      out.write("        { x: 40, y: 65 },\r\n");
      out.write("        { x: 50, y: 95 },\r\n");
      out.write("        { x: 60, y: 68 },\r\n");
      out.write("        { x: 70, y: 28 },\r\n");
      out.write("        { x: 80, y: 34 },\r\n");
      out.write("        { x: 90, y: 14}\r\n");
      out.write("        ]\r\n");
      out.write("      }        \r\n");
      out.write("      ]\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    chart.render();\r\n");
      out.write("  }\r\n");
      out.write("  </script> -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body ng-controller=\"DashboardCtrl\">\r\n");
      out.write("\t<div id=\"masterload\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<p>From: <input type=\"text\" id=\"datepickerFrom\" style=\"width:120px\"> &nbsp &nbsp To: <input type=\"text\" id=\"datepickerTo\" style=\"width:120px\"> &nbsp &nbsp <button type=\"button\" ng-click=\"dateApply()\" class=\"btn btn-primary\" style=\"height:31px\">Submit</button></p>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<nvd3 options=\"options\" data=\"data\"></nvd3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<canvas id=\"barChart\"></canvas>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<h3>Raw Material</h3>\r\n");
      out.write("\t\t\t<table id=\"example\" class=\"table table-striped table-bordered\" style=\"width:100%\">\r\n");
      out.write("\t\t        <thead>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <th>S.No</th>\r\n");
      out.write("\t\t                <th>Prod_Name</th>\r\n");
      out.write("\t\t                <th>Quantity</th>\r\n");
      out.write("\t\t                <th>Price</th>\r\n");
      out.write("\t\t                <th>Date</th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </thead>\r\n");
      out.write("\t        \t<tbody>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>01</td>\r\n");
      out.write("\t\t                <td>Anti-Scale Chemical</td>\r\n");
      out.write("\t\t                <td>61</td>\r\n");
      out.write("\t\t                <td>320,800</td>\r\n");
      out.write("\t\t                <td>2018/03/15</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t                <td>02</td>\r\n");
      out.write("\t\t                <td>Cap</td>\r\n");
      out.write("\t\t                <td>63</td>\r\n");
      out.write("\t\t                <td>170</td>\r\n");
      out.write("\t\t                <td>2018/02/25</td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t            </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script\tsrc=\"external-js/excanvas.min.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"external-js/jquery.flot.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"external-js/jquery.flot.pie.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"external-js/jquery.flot.resize.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"external-js/jquery.flot.time.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"external-js/jquery.flot.tooltip.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
