/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-03-24 17:42:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/HomePageStyle.css\">\r\n");
      out.write("<script\tsrc=\"external-js/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#Login').click(function() {\r\n");
      out.write("\t\t\t\tvar logindata = {\r\n");
      out.write("\t\t\t\t\tusername : $('#username').val(),\r\n");
      out.write("\t\t\t\t\tpassword : $('#password').val(),\r\n");
      out.write("\t\t\t\t\tkeyword : \"logincheck\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t$.post('Login', $.param(logindata), function(response) {\r\n");
      out.write("\t\t\t\t\tif(response != \"Invalid\"){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"Menu.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"Invalid Credentials\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<title>Home Page - Water Plant</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class = \"container col-md-12\">\r\n");
      out.write("  \t\t<div class=\"col-md-6\">\r\n");
      out.write("    \t\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("      \t\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("        \t\t\t<div class=\"item active\">\r\n");
      out.write("          \t\t\t\t<img class=\"first-slide\" src=\"images/1.jpg\" alt=\"First slide\">\r\n");
      out.write("          \t\t\t\t<!-- In case you want some caption on your slide, uncomment this section here\r\n");
      out.write("          \t\t\t\t<div class=\"container\">\r\n");
      out.write("            \t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("              \t\t\t\t\t<h1>Example headline.</h1>\r\n");
      out.write("              \t\t\t\t\t<p>Note: If you're viewing this page via a <code>file://</code> URL, the \"next\" and \"previous\" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("          \t\t\t\t</div>-->\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t<div class=\"item\">\r\n");
      out.write("          \t\t\t\t<img class=\"second-slide\" src=\"http://xtribune.com/wp-content/uploads/2015/06/o-BOTTLED-WATER-facebook.jpg\" alt=\"Second slide\">\r\n");
      out.write("          \t\t\t\t<!-- In case you want some caption with button on your slide, uncomment this section here          \r\n");
      out.write("          \t\t\t\t<div class=\"container\">\r\n");
      out.write("            \t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("            \t\t \t\t\t<h1>Another example headline.</h1>\r\n");
      out.write("              \t\t\t\t\t<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("              \t\t\t\t\t<p><a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Learn more</a></p>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("          \t\t\t\t</div> -->\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t<div class=\"item\">\r\n");
      out.write("          \t\t\t\t<img class=\"third-slide\" src=\"images/21_2_1.jpg\" alt=\"Third slide\">\r\n");
      out.write("          \t\t\t\t<!-- In case you want some caption with button on your slide, uncomment this section here              \r\n");
      out.write("          \t\t\t\t<div class=\"container\">\r\n");
      out.write("          \t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("              \t\t\t\t\t<h1>One more for good measure.</h1>\r\n");
      out.write("              \t\t\t\t\t<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("              \t\t\t\t\t<p><a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Browse gallery</a></p>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("          \t\t\t\t</div> -->\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("        \t\t\t<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("        \t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("      \t\t\t</a>\r\n");
      out.write("      \t\t\t<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("        \t\t\t<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        \t\t\t<span class=\"sr-only\">Next</span>\r\n");
      out.write("      \t\t\t</a>\r\n");
      out.write("    \t\t</div><!-- /.carousel -->\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"col-md-6\">\r\n");
      out.write("              <h2 class=\"featurette-heading\">Water Plant Automation <span class=\"text-muted\">It'll blow your mind.</span></h2>\r\n");
      out.write("          \t  <p class=\"lead\">Welcome to the interactive site of Water Plant. A place where you can\r\n");
      out.write("\t\t\tvisualize how process works.It is the one which makes your work more easier and faster forever.<br>To further explore, kindly <a\r\n");
      out.write("\t\t\t\tdata-toggle=\"modal\" data-target=\"#myModal\">LOGIN HERE</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">Login</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body  \">\r\n");
      out.write("\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control \" name=\"username\" id=\"username\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Username\" required autofocus />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-briefcase\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" class=\"form-control \" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" size=\"14\" placeholder=\"Enter Password\" required />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" name=\"action\" value=\"Login\" id=\"Login\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-info\">Login</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
