/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-03-24 17:44:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Water Plant - Home</title>\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/metisMenu.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/CustomStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/CarouselStyle.css\">\r\n");
      out.write("<script\tsrc=\"external-js/jquery.min.js\"></script>\t\r\n");
      out.write("<script\tsrc=\"external-js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/metisMenu.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\"\r\n");
      out.write("\t\t\tstyle=\"margin-bottom: 0\">\r\n");
      out.write("\t\t<div class=\"navbar-header \">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"Menu.jsp\">Water Plant</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navbar-default sidebar\" role=\"navigation\" >\r\n");
      out.write("\t\t\t<div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav\" id=\"side-menu\" style=\"color:white\">\r\n");
      out.write("\t\t\t\t\t<li class=\"sidebar-search\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group custom-search-form form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"fa fa-search\"></i></span> <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Dashboard.jsp\"><i class=\"fa fa-dashboard fa-fw\"></i> Dashboard</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Rawmaterial.jsp\"><i class=\"fa fa-briefcase\"></i> Raw Material</a>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Stock.jsp\"><i class=\"fa fa-bar-chart-o fa-fw\"></i> Stock</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Billing.jsp\"><i class=\"fa fa-credit-card fa-fw\"></i> Billing</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Expense.jsp\"><i class=\"fa fa-inr fa-fw\"></i> Expense</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Customer.jsp\"><i class=\"fa fa-address-book fa-fw\"></i> Customer</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"session\">\r\n");
      out.write("\t\t<p class=\"navbar-brand\" style=\"font-size:13px\">Welcome, <b>");
      out.print(session.getAttribute("username") );
      out.write("</b></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id=\"button\">\r\n");
      out.write("\t<button id=\"logout\" class=\"navbar-brand btn btn-link\" style=\"font-size:14px\"><i class=\"fa fa-sign-out\"> Logout</i></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t </nav>\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- \t<div id=\"masterhead\"> -->\r\n");
      out.write("<!-- \t<div class=\"container\"> -->\r\n");
      out.write("<!-- \t\t<div class=\"slideshow\"> -->\r\n");
      out.write("<!-- \t\t\t<div id=\"slideshow\" class=\"carousel slide\" data-ride=\"carousel\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"carousel-inner\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<h3 align=\"middle\">WaTeR PlAnT</h3> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"item active\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<img class=\"img-responsive\" src=\"http://mechmannindia.com/images/magazine/30.jpg\" alt=\"First Slide\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"container\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<div class=\"carousel-caption\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<h1>Filling</h1> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div>/. Item Active -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"item\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<img class=\"img-responsive\" src=\"https://ak4.picdn.net/shutterstock/videos/15852514/thumb/1.jpg\" width=\"50px\" alt=\"Second Slide\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"container\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<div class=\"carousel-caption\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<h1>Packing</h1> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div>/. Item -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"item\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<img class=\"img-responsive\" src=\"https://www.dewarplumbers.ie/wp-content/uploads/2014/04/canstockphoto-water-bottle.jpg\" alt=\"Third slide\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"container\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<div class=\"carousel-caption\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<h1>Drinking</h1> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div>/. Item -->\r\n");
      out.write("<!-- \t\t\t\t</div>/. Carousel-Inner -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"controlsBlock\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"controls\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<a class=\"left carousel-control\" href=\"#slideshow\" data-slide=\"prev\"><span class=\"glyphicon glyphicon-chevron-left\"></span></a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<a class=\"right carousel-control\" href=\"#slideshow\" data-slide=\"next\"><span class=\"glyphicon glyphicon-chevron-right\"></span></a> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<a class=\"left carousel-control\" href=\"#slideshow\" data-slide=\"prev\"><i class=\"fa fa-chevron-left\"></i></a>\r\n");
      out.write("<!--  \t\t\t\t\t\t<a class=\"right carousel-control\" href=\"#slideshow\" data-slide=\"next\"><i class=\"fa fa-chevron-right\"></i></a>--> \r\n");
      out.write("<!-- \t\t\t\t\t\t<div class=\"carousel-indicators\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li data-target=\"#slideshow\" data-slide-to=\"0\" class=\"active\"></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li data-target=\"#slideshow\" data-slide-to=\"1\"></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li data-target=\"#slideshow\" data-slide-to=\"2\"></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t</div>/# Slideshow .Carousel -->\r\n");
      out.write("<!-- \t\t</div>/. Slideshow -->\r\n");
      out.write("<!-- \t</div>/. Container -->\r\n");
      out.write("<!-- </div>/# Mastehead -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$('#side-menu').metisMenu();\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#logout').click(function(){\r\n");
      out.write("\t\t\t$.post(\"Logout\",function(response){\r\n");
      out.write("\t\t\t\twindow.location.href=\"Homepage.jsp\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("// \t$('#slideshow').carousel({\r\n");
      out.write("//         interval: 5000\r\n");
      out.write("//      });\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
