/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-03-24 17:44:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.we5.waterplant.javaclass.GetRawmaterial;
import java.util.ArrayList;
import java.util.List;

public final class Rawmaterial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/responsive.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/metisMenu.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script\tsrc=\"external-js/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/bootstrap.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"external-js/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"JS/RawmaterialScript.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('#excelbutton').click(function(){\r\n");
      out.write("        var url='data:application/vnd.ms-excel,' + encodeURIComponent($('#mytable').html()) \r\n");
      out.write("        location.href=url\r\n");
      out.write("        return false\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<title>Raw material - Water Plant</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"masterload\"></div>\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"container col-md-10 form-group\">\r\n");
      out.write("\t\t\t<div class=\"row panel panel-default\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-top: 20px; padding: 20px\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<table width=\"100%\"\r\n");
      out.write("\t\t\t\t\tclass=\"panel panel-default table table-striped table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\tid=\"mytable\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Vendor Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Product Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Product Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-4 form-group\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn btn-primary col-md-3\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"modal\" value=\"Add Product\" data-target=\"#myModal\">&nbsp;\r\n");
      out.write("\t\t\t\t");

					if (session.getAttribute("checkrole").equals("Admin")) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-offset-1 btn btn-primary col-md-3\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#myModal3\">Add Vendor</button>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"excelbutton\" class=\"btn btn-primary col-md-3\">Export</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"modal-title\">Add Product</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body  \">\r\n");
      out.write("\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> </span> <input -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"vendorname\" id=\"addvendor\" -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\tsize=\"14\" placeholder=\"Vendor Name\" required autofocus /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> </span> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"vendordrop\" id=\"vendordrop\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>--Select Vendor --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></i> </span> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"dropdown\" id=\"dropdown\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>--Select Product--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"adddesc\" id=\"adddesc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"14\" rows=\"2\" cols=\"50\" placeholder=\"Description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"quantity\" id=\"addquantity\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"14\" type=\"number\" placeholder=\"Quantity\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-usd\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"price\" id=\"addprice\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"number\" placeholder=\"Price\" min=\"1\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"addbutton\" name=\"Add\" value=\"Add\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-info\">Add</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"myModal2\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"modal-title\">Edit Product</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"vendorname\" id=\"venname\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Vendor Name\" required autofocus />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></i> </span> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"dropdown\" id=\"dropdown2\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>--Select Product--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"editdesc\" id=\"editdesc\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsize=\"14\" rows=\"2\" cols=\"50\" placeholder=\"Description\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"quantity\" size=\"14\" id=\"qtyname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"number\" placeholder=\"Quantity\" min=\"1\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-usd\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"price\" size=\"14\" id=\"priname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"number\" placeholder=\"Price\" min=\"1\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" name=\"Add\" value=\"Add\" id=\"editclick\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-info\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal3\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">Add Vendor</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"vendorname\" id=\"newvenname\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Vendor Name\" required autofocus />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"companyname\" id=\"newcompanyname\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsize=\"14\" placeholder=\"Company Name\" required />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"email\" size=\"14\" id=\"newemail\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"email\" placeholder=\"Email\" required />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-usd\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"mobilenumber\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"newmobilenumber\" type=\"number\" placeholder=\"Mobile Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" name=\"Add\" value=\"Add\" id=\"addnewvendor\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-info\">Add</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
