/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2018-03-24 17:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.we5.waterplant.javaclass.StockMaterial;
import java.util.ArrayList;
import java.util.List;

public final class Stock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/metisMenu.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"external-js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"external-js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"external-js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"external-js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"external-js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script src=\"external-js/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<title>Stock material - Water Plant</title>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#masterload').load(\"Menu.jsp\");\r\n");
      out.write("\t\t//document.getElementById(\"date\").valueAsDate=new Date();\r\n");
      out.write("\t\t$.post(\"Stock\",{pageload:\"getStock\"},function(response){\r\n");
      out.write("\t\t\t\t//alert(response)\r\n");
      out.write("\t\t\t\tif (response != null) {\r\n");
      out.write("\t\t\t\t\t$.noConflict();\r\n");
      out.write("\t\t\t\t\ttable=$('#mytable').DataTable({\r\n");
      out.write("\t\t\t\t\t\t//destroy : true,\r\n");
      out.write("\t\t\t\t\t\tresponsive : true,\r\n");
      out.write("\t\t\t\t\t\tdata : response,\r\n");
      out.write("\t\t\t\t\t\tcolumnDefs:[\r\n");
      out.write("\t\t\t\t\t\t\t\t\t{\t\"targets\":-1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"data\":null,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdefaultContent:\"<button type='button' class='editbutton btn btn-primary' ><span class='glyphicon glyphicon-edit'></span></button> | <button type='button' class='deletebutton btn btn-primary'><span class='glyphicon glyphicon-trash'></span></button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t\t\t\t\t\"pageLength\" : 5,\r\n");
      out.write("\t\t\t\t\t\t\"lengthMenu\" : [ 5, 10, 25, 50 ]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#addstock').click(function(){\r\n");
      out.write("\t\t\tvar data={\r\n");
      out.write("\t\t\t\t\tstockname:$('#stockname').val(),\r\n");
      out.write("\t\t\t\t\tqty:$('#qty').val(),\r\n");
      out.write("\t\t\t\t\tdate:$('#date').val(),\r\n");
      out.write("\t\t\t\t\tpageload:\"addstock\"\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$.post('Stock',$.param(data),function(response){\r\n");
      out.write("\t\t\t\tif(response == \"1\"){\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#date').datepicker({\r\n");
      out.write("\t\t    dateFormat: 'yy-mm-dd'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#date\").focus(function(){\r\n");
      out.write("\t\t\t$(\"#ui-datepicker-div\").css(\"z-index\", \"9999\");\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#addStockButton\").bind(\"click\", function(){\r\n");
      out.write("\t\t\t$(\"#editDiv\").hide();\r\n");
      out.write("\t\t\t$(\"#addDiv\").show();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\", \".editbutton\", function(){\r\n");
      out.write("\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\tvar tableData = $(this).closest('tr')\r\n");
      out.write("            .find('td')\r\n");
      out.write("            .map(function() {\r\n");
      out.write("\t\t\t\treturn $(this).text();\r\n");
      out.write("\t\t\t\t}).get(); \r\n");
      out.write("\t\t\t$(\"#stockname\").val(tableData[1]);\r\n");
      out.write("\t\t\t$(\"#qty\").val(tableData[2]);  \r\n");
      out.write("\t\t\t$(\"#editDiv\").show();\r\n");
      out.write("\t\t\t$(\"#addDiv\").hide();\r\n");
      out.write("\t\t\t$(\"#stockId\").val(tableData[0]);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\", \"#editStock\", function(){\r\n");
      out.write("\t\t\t  var data={\r\n");
      out.write("\t\t\t\t\t  \tstockId:$(\"#stockId\").val(),\r\n");
      out.write("\t\t\t\t\t\tstockname:$(\"#stockname\").val(),\r\n");
      out.write("\t\t\t\t\t\tqty:$(\"#qty\").val(),\r\n");
      out.write("\t\t\t\t\t\tpageload:\"editStock\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t$.post('Stock',$.param(data),function(response){\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t\tif(response == \"1\"){\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"click\", \".deletebutton\", function(){\r\n");
      out.write("\t\t\talert(\"delete\");\r\n");
      out.write("\t\t\tvar tableData = $(this).closest('tr')\r\n");
      out.write("            .find('td')\r\n");
      out.write("            .map(function() {\r\n");
      out.write("\t\t\t\treturn $(this).text();\r\n");
      out.write("\t\t\t\t}).get(); \r\n");
      out.write("\t\t\t  var data={\r\n");
      out.write("\t\t\t\t\t  \tstockId:tableData[0],\r\n");
      out.write("\t\t\t\t\t\tpageload:\"deletStock\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t$.post('Stock',$.param(data),function(response){\r\n");
      out.write("\t\t\t\t\talert(response);\r\n");
      out.write("\t\t\t\t\tif(response == true){\r\n");
      out.write("\t\t\t\t\t\talert(\"deleting record\");\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t});\t  \t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"masterload\"></div>\r\n");
      out.write("\t<!-- Place the code inside the below div tag -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"container col-md-10\">\r\n");
      out.write("\t\t\t<div class=\"row panel panel-default\"\r\n");
      out.write("\t\t\t\tstyle=\"margin-top: 20px; padding: 20px\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<table width=\"100%\"\r\n");
      out.write("\t\t\t\t\tclass=\"panel panel-default table table-striped table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\tid=\"mytable\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>StockID</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Stock Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Price</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Total</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-5 col-md-3\">\r\n");
      out.write("\t\t\t\t<input id=\"addStockButton\" type=\"button\" class=\"btn btn-default\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\tvalue=\"Add Stock\" data-target=\"#myModal\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-content \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"modal-title\">Add Stock</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"StockName\" size=\"14\" id=\"stockname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Stock Name\" required autofocus />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> </span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" name=\"quantity\" size=\"14\" type=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"qty\" placeholder=\"Quantity\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon \"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-calendar\"></i> </span> <input type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"date\" class=\"form-control\" name=\"Date\" size=\"14\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Date\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"stockId\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\" id=\"addDiv\"> \r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"Addstock\" value=\"Addstock\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"addstock\" class=\"btn btn-info\">Add</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\" id=\"editDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" name=\"editStock\" value=\"Addstock\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"editStock\" class=\"btn btn-info\">Edit</button>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
